//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.7.0
//     from Assets/Settings/PlayerControl/PlayerControl.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @PlayerControl: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @PlayerControl()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""PlayerControl"",
    ""maps"": [
        {
            ""name"": ""Input"",
            ""id"": ""91d8b77e-9ede-4f58-8d9c-a5aaa1e02715"",
            ""actions"": [
                {
                    ""name"": ""DialogConfirm"",
                    ""type"": ""Button"",
                    ""id"": ""fd2560b8-742b-4a1a-8462-ec6a637e8edd"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""KeyboardSelect"",
                    ""type"": ""Value"",
                    ""id"": ""aba52e20-2e67-4a09-abe0-69a81d3ddb2d"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""SelectConfirm"",
                    ""type"": ""Button"",
                    ""id"": ""dc5a8392-33c2-4df1-b8e8-6e0b4ff64e2e"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SelectBack"",
                    ""type"": ""Button"",
                    ""id"": ""5595e64a-d052-4839-9353-002931e8ec63"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""MouseMove"",
                    ""type"": ""PassThrough"",
                    ""id"": ""b3723d03-5f58-4bff-85ec-0ee0de3969b5"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""83260b16-346e-4b51-9085-8a8d25bf9ebc"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DialogConfirm"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""55f8f421-429c-4561-9fd7-aa5c670653a2"",
                    ""path"": ""<Mouse>/press"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DialogConfirm"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""Direction"",
                    ""id"": ""63d3e7a4-7cb9-425b-ba2c-b60553b883a0"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""KeyboardSelect"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""3630d3f7-285e-4995-b086-3db79348fe7c"",
                    ""path"": ""<Keyboard>/upArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""KeyboardSelect"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""86433f98-f2f4-4580-9266-2436c6e6aa35"",
                    ""path"": ""<Keyboard>/downArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""KeyboardSelect"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""897122b9-832d-4821-9f2e-31d072ab6806"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""KeyboardSelect"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""52639c32-f3e2-48fb-a0af-5cdfd4fc6a91"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""KeyboardSelect"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""92d3696f-854e-49ce-908c-fb402c11ab12"",
                    ""path"": ""<Keyboard>/enter"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SelectConfirm"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""381e27ac-c117-4991-b31b-83901eb817eb"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SelectConfirm"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b78366a0-a252-40e5-bcdc-bff81fcd61b2"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SelectBack"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""818acc33-cb91-4b72-8649-1ec75942afe8"",
                    ""path"": ""<Mouse>/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MouseMove"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Input
        m_Input = asset.FindActionMap("Input", throwIfNotFound: true);
        m_Input_DialogConfirm = m_Input.FindAction("DialogConfirm", throwIfNotFound: true);
        m_Input_KeyboardSelect = m_Input.FindAction("KeyboardSelect", throwIfNotFound: true);
        m_Input_SelectConfirm = m_Input.FindAction("SelectConfirm", throwIfNotFound: true);
        m_Input_SelectBack = m_Input.FindAction("SelectBack", throwIfNotFound: true);
        m_Input_MouseMove = m_Input.FindAction("MouseMove", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Input
    private readonly InputActionMap m_Input;
    private List<IInputActions> m_InputActionsCallbackInterfaces = new List<IInputActions>();
    private readonly InputAction m_Input_DialogConfirm;
    private readonly InputAction m_Input_KeyboardSelect;
    private readonly InputAction m_Input_SelectConfirm;
    private readonly InputAction m_Input_SelectBack;
    private readonly InputAction m_Input_MouseMove;
    public struct InputActions
    {
        private @PlayerControl m_Wrapper;
        public InputActions(@PlayerControl wrapper) { m_Wrapper = wrapper; }
        public InputAction @DialogConfirm => m_Wrapper.m_Input_DialogConfirm;
        public InputAction @KeyboardSelect => m_Wrapper.m_Input_KeyboardSelect;
        public InputAction @SelectConfirm => m_Wrapper.m_Input_SelectConfirm;
        public InputAction @SelectBack => m_Wrapper.m_Input_SelectBack;
        public InputAction @MouseMove => m_Wrapper.m_Input_MouseMove;
        public InputActionMap Get() { return m_Wrapper.m_Input; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(InputActions set) { return set.Get(); }
        public void AddCallbacks(IInputActions instance)
        {
            if (instance == null || m_Wrapper.m_InputActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_InputActionsCallbackInterfaces.Add(instance);
            @DialogConfirm.started += instance.OnDialogConfirm;
            @DialogConfirm.performed += instance.OnDialogConfirm;
            @DialogConfirm.canceled += instance.OnDialogConfirm;
            @KeyboardSelect.started += instance.OnKeyboardSelect;
            @KeyboardSelect.performed += instance.OnKeyboardSelect;
            @KeyboardSelect.canceled += instance.OnKeyboardSelect;
            @SelectConfirm.started += instance.OnSelectConfirm;
            @SelectConfirm.performed += instance.OnSelectConfirm;
            @SelectConfirm.canceled += instance.OnSelectConfirm;
            @SelectBack.started += instance.OnSelectBack;
            @SelectBack.performed += instance.OnSelectBack;
            @SelectBack.canceled += instance.OnSelectBack;
            @MouseMove.started += instance.OnMouseMove;
            @MouseMove.performed += instance.OnMouseMove;
            @MouseMove.canceled += instance.OnMouseMove;
        }

        private void UnregisterCallbacks(IInputActions instance)
        {
            @DialogConfirm.started -= instance.OnDialogConfirm;
            @DialogConfirm.performed -= instance.OnDialogConfirm;
            @DialogConfirm.canceled -= instance.OnDialogConfirm;
            @KeyboardSelect.started -= instance.OnKeyboardSelect;
            @KeyboardSelect.performed -= instance.OnKeyboardSelect;
            @KeyboardSelect.canceled -= instance.OnKeyboardSelect;
            @SelectConfirm.started -= instance.OnSelectConfirm;
            @SelectConfirm.performed -= instance.OnSelectConfirm;
            @SelectConfirm.canceled -= instance.OnSelectConfirm;
            @SelectBack.started -= instance.OnSelectBack;
            @SelectBack.performed -= instance.OnSelectBack;
            @SelectBack.canceled -= instance.OnSelectBack;
            @MouseMove.started -= instance.OnMouseMove;
            @MouseMove.performed -= instance.OnMouseMove;
            @MouseMove.canceled -= instance.OnMouseMove;
        }

        public void RemoveCallbacks(IInputActions instance)
        {
            if (m_Wrapper.m_InputActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IInputActions instance)
        {
            foreach (var item in m_Wrapper.m_InputActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_InputActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public InputActions @Input => new InputActions(this);
    public interface IInputActions
    {
        void OnDialogConfirm(InputAction.CallbackContext context);
        void OnKeyboardSelect(InputAction.CallbackContext context);
        void OnSelectConfirm(InputAction.CallbackContext context);
        void OnSelectBack(InputAction.CallbackContext context);
        void OnMouseMove(InputAction.CallbackContext context);
    }
}
